name: Pull request check

on: [pull_request]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
        
      - name: "Flutter Analyze"
        run: flutter analyze .
        
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
        
      - name: "Flutter Format"
        run: flutter format .
        
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
        
      - name: "Flutter Test"
        run: flutter test
    
