name: Pull request check

on: [pull_request]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
          
      - name: Configuring melos and bootstrap project
        uses: bluefireteam/melos-action@v2
        
      - name: "Flutter Analyze"
        run: melos run analyze
        
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
          
      - name: Configuring melos and bootstrap project
        uses: bluefireteam/melos-action@v2
        
      - name: "Flutter Format"
        run: melos run format -- --set-exit-if-changed
        
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configuring Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
          
      - name: Configuring melos and bootstrap project
        uses: bluefireteam/melos-action@v2
        
      - name: "Flutter Test"
        run: melos run test
    
